default: &default
  adapter:  postgresql
  pool:     <%= ENV['POSTGRES_POOL'] || 5 %>
  encoding: unicode

development:
  <<: *default
  database: baby_names_development

test:
  <<: *default
  database: baby_names_test

production:
  <<: *default
  database: baby_names_production
